[2022-07-02 19:12:49,805] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ai_cluster.create_job_flow manual__2022-07-02T13:42:47.887514+00:00 [queued]>
[2022-07-02 19:12:49,809] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ai_cluster.create_job_flow manual__2022-07-02T13:42:47.887514+00:00 [queued]>
[2022-07-02 19:12:49,809] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-02 19:12:49,809] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-02 19:12:49,809] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-02 19:12:49,816] {taskinstance.py:1377} INFO - Executing <Task(EmrCreateJobFlowOperator): create_job_flow> on 2022-07-02 13:42:47.887514+00:00
[2022-07-02 19:12:49,819] {standard_task_runner.py:52} INFO - Started process 61387 to run task
[2022-07-02 19:12:49,823] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'ai_cluster', 'create_job_flow', 'manual__2022-07-02T13:42:47.887514+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/itvghapipeline.py', '--cfg-path', '/var/folders/n4/66bq258d6xq6lscwjlgs6q500000gn/T/tmpz1xfh_yq', '--error-file', '/var/folders/n4/66bq258d6xq6lscwjlgs6q500000gn/T/tmpyk310t7y']
[2022-07-02 19:12:49,824] {standard_task_runner.py:80} INFO - Job 3: Subtask create_job_flow
[2022-07-02 19:12:49,856] {task_command.py:370} INFO - Running <TaskInstance: ai_cluster.create_job_flow manual__2022-07-02T13:42:47.887514+00:00 [running]> on host itversitys-mbp.lan
[2022-07-02 19:12:49,896] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ai_cluster
AIRFLOW_CTX_TASK_ID=create_job_flow
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T13:42:47.887514+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-02T13:42:47.887514+00:00
[2022-07-02 19:12:49,896] {emr.py:323} INFO - Creating JobFlow using aws-conn-id: aws_default, emr-conn-id: emr_default
[2022-07-02 19:12:49,900] {base.py:68} INFO - Using connection ID 'emr_default' for task execution.
[2022-07-02 19:12:49,903] {base.py:68} INFO - Using connection ID 'aws_default' for task execution.
[2022-07-02 19:12:49,923] {credentials.py:1311} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2022-07-02 19:12:51,580] {emr.py:337} INFO - JobFlow with id j-3I2L0JLIMNGHH created
[2022-07-02 19:12:51,596] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=ai_cluster, task_id=create_job_flow, execution_date=20220702T134247, start_date=20220702T134249, end_date=20220702T134251
[2022-07-02 19:12:51,641] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-02 19:12:51,656] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
