[2022-07-02 21:51:58,843] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ai_cluster.check_job_flow manual__2022-07-02T16:21:53.958512+00:00 [queued]>
[2022-07-02 21:51:58,847] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ai_cluster.check_job_flow manual__2022-07-02T16:21:53.958512+00:00 [queued]>
[2022-07-02 21:51:58,847] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-02 21:51:58,847] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-02 21:51:58,847] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-02 21:51:58,855] {taskinstance.py:1377} INFO - Executing <Task(EmrJobFlowSensor): check_job_flow> on 2022-07-02 16:21:53.958512+00:00
[2022-07-02 21:51:58,857] {standard_task_runner.py:52} INFO - Started process 94444 to run task
[2022-07-02 21:51:58,861] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'ai_cluster', 'check_job_flow', 'manual__2022-07-02T16:21:53.958512+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/itvghapipeline.py', '--cfg-path', '/var/folders/n4/66bq258d6xq6lscwjlgs6q500000gn/T/tmp3nlli9ca', '--error-file', '/var/folders/n4/66bq258d6xq6lscwjlgs6q500000gn/T/tmpq2x8zowl']
[2022-07-02 21:51:58,862] {standard_task_runner.py:80} INFO - Job 11: Subtask check_job_flow
[2022-07-02 21:51:58,898] {task_command.py:370} INFO - Running <TaskInstance: ai_cluster.check_job_flow manual__2022-07-02T16:21:53.958512+00:00 [running]> on host itversitys-mbp.lan
[2022-07-02 21:51:58,951] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ai_cluster
AIRFLOW_CTX_TASK_ID=check_job_flow
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T16:21:53.958512+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-02T16:21:53.958512+00:00
[2022-07-02 21:51:58,957] {base.py:68} INFO - Using connection ID 'aws_default' for task execution.
[2022-07-02 21:51:58,999] {credentials.py:1311} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2022-07-02 21:51:59,048] {emr.py:235} INFO - Poking cluster j-241O8GL0VVC94
[2022-07-02 21:52:00,029] {emr.py:74} INFO - Job flow currently STARTING
[2022-07-02 21:53:00,039] {emr.py:235} INFO - Poking cluster j-241O8GL0VVC94
[2022-07-02 21:53:01,068] {emr.py:74} INFO - Job flow currently STARTING
[2022-07-02 21:54:01,071] {emr.py:235} INFO - Poking cluster j-241O8GL0VVC94
[2022-07-02 21:54:02,168] {emr.py:74} INFO - Job flow currently STARTING
[2022-07-02 21:55:02,171] {emr.py:235} INFO - Poking cluster j-241O8GL0VVC94
[2022-07-02 21:55:03,260] {emr.py:74} INFO - Job flow currently STARTING
[2022-07-02 21:56:03,263] {emr.py:235} INFO - Poking cluster j-241O8GL0VVC94
[2022-07-02 21:56:04,565] {emr.py:74} INFO - Job flow currently STARTING
[2022-07-02 21:57:04,568] {emr.py:235} INFO - Poking cluster j-241O8GL0VVC94
[2022-07-02 21:57:05,721] {emr.py:74} INFO - Job flow currently WAITING
[2022-07-02 21:58:05,724] {emr.py:235} INFO - Poking cluster j-241O8GL0VVC94
[2022-07-02 21:58:06,848] {emr.py:74} INFO - Job flow currently WAITING
[2022-07-02 21:59:06,850] {emr.py:235} INFO - Poking cluster j-241O8GL0VVC94
[2022-07-02 21:59:08,044] {emr.py:74} INFO - Job flow currently WAITING
[2022-07-02 22:00:08,047] {emr.py:235} INFO - Poking cluster j-241O8GL0VVC94
[2022-07-02 22:00:09,123] {emr.py:74} INFO - Job flow currently WAITING
[2022-07-02 22:01:09,126] {emr.py:235} INFO - Poking cluster j-241O8GL0VVC94
[2022-07-02 22:01:10,136] {emr.py:74} INFO - Job flow currently WAITING
[2022-07-02 22:02:10,138] {emr.py:235} INFO - Poking cluster j-241O8GL0VVC94
[2022-07-02 22:02:11,345] {emr.py:74} INFO - Job flow currently WAITING
[2022-07-02 22:02:48,833] {local_task_job.py:220} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-07-02 22:02:48,848] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 94444. PIDs of all processes in the group: [94444]
[2022-07-02 22:02:48,848] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 94444
[2022-07-02 22:02:48,848] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-07-02 22:02:48,862] {process_utils.py:75} INFO - Process psutil.Process(pid=94444, status='terminated', exitcode=0, started='21:51:58') (94444) terminated with exit code 0
